### ISSUE TITLE
Users are not added to database

### ISSUE THREAD

**Issue by DavidMorp** [bodsch/ansible-icingaweb2#13]
I am unable to get the users defined in the vars to be added to the database. I have been trying to debug it myself but I'm at a loss.
I have modified the task to remove potential issues with the vars:
```
- name: test import icingaweb into database
  become: true
  icingaweb_database_user:
    state: 'present'
    username: 'hard'
    password: 'coded'
    force: true
    database_login_host: "{{ icingaweb_auth_backend.database.host }}"
    database_name: "{{ icingaweb_auth_backend.database.dbname }}"
    database_config_file: /etc/icingaweb2/.my.cnf
  # no_log: true
  register: import_icingaweb2_users
  when:
    - icingaweb_auth_backend is defined
    - icingaweb_auth_backend.database is defined
    - icingaweb_auth_backend.database.host is defined
    - icingaweb_auth_backend.database.dbname is defined
```
And ran: `ansible-playbook playbook.yml -i inventory --tags "icingaweb_configure" -vvvv`
```
TASK [icingaweb : test import icingaweb into database] *********************************************************************************************************************************************************
task path: /Users/david/Repos/ansible-icinga2-aio-deploy/roles/icingaweb/tasks/configure.yml:134
Wednesday 16 June 2021  10:14:38 +0200 (0:00:10.265)       0:01:10.861 ********
<10.0.0.99> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.0.0.99> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/david/.ssh/icinga-ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/david/.ansible/cp/da87df5b65 10.0.0.99 '/bin/sh -c '"'"'echo ~ansible && sleep 0'"'"''
<10.0.0.99> (0, b'/home/ansible\n', b'OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/david/.ssh/config\r\ndebug1: /Users/david/.ssh/config line 1: Applying options for 10.59.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.0.0.99 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25787\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.0.99> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.0.0.99> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/david/.ssh/icinga-ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/david/.ansible/cp/da87df5b65 10.0.0.99 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049 `" && echo ansible-tmp-1623831279.150812-26120-146535079938049="` echo /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049 `" ) && sleep 0'"'"''
<10.0.0.99> (0, b'ansible-tmp-1623831279.150812-26120-146535079938049=/home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049\n', b'OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/david/.ssh/config\r\ndebug1: /Users/david/.ssh/config line 1: Applying options for 10.59.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.0.0.99 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25787\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
Using module file /Users/david/Repos/ansible-icinga2-aio-deploy/roles/icingaweb/library/icingaweb_database_user.py
<10.0.0.99> PUT /Users/david/.ansible/tmp/ansible-local-25779hj3i6udd/tmpxrgsniqh TO /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/AnsiballZ_icingaweb_database_user.py
<10.0.0.99> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/david/.ssh/icinga-ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/david/.ansible/cp/da87df5b65 '[10.0.0.99]'
<10.0.0.99> (0, b'sftp> put /Users/david/.ansible/tmp/ansible-local-25779hj3i6udd/tmpxrgsniqh /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/AnsiballZ_icingaweb_database_user.py\n', b'OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/david/.ssh/config\r\ndebug1: /Users/david/.ssh/config line 1: Applying options for 10.59.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.0.0.99 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25787\r\ndebug3: mux_client_request_session: session request sent\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 3 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/ansible size 0\r\ndebug3: Looking up /Users/david/.ansible/tmp/ansible-local-25779hj3i6udd/tmpxrgsniqh\r\ndebug3: Sent message fd 3 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/AnsiballZ_icingaweb_database_user.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:26770\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 32768 bytes at 65536\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 7 26770 bytes at 98304\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.0.99> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.0.0.99> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/david/.ssh/icinga-ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/david/.ansible/cp/da87df5b65 10.0.0.99 '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/ /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/AnsiballZ_icingaweb_database_user.py && sleep 0'"'"''
<10.0.0.99> (0, b'', b'OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/david/.ssh/config\r\ndebug1: /Users/david/.ssh/config line 1: Applying options for 10.59.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.0.0.99 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25787\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.0.0.99> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.0.0.99> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/david/.ssh/icinga-ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/david/.ansible/cp/da87df5b65 -tt 10.0.0.99 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=zqmjdndqmlossqqmvjppocmxscvlibul] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-zqmjdndqmlossqqmvjppocmxscvlibul ; /usr/bin/python3 /home/ansible/.ansible/tmp/ansible-tmp-1623831279.150812-26120-146535079938049/AnsiballZ_icingaweb_database_user.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<10.0.0.99> (0, b'\r\n{"changed": true, "failed": false, "ansible_module_results": "none", "invocation": {"module_args": {"state": "present", "username": "hard", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "force": true, "database_login_host": "10.0.0.96", "database_name": "icingaweb_config", "database_config_file": "/etc/icingaweb2/.my.cnf", "database_login_port": 3306, "preferences": null, "database_login_user": null, "database_login_password": null, "database_login_unix_socket": null}}}\r\n', b'OpenSSH_8.1p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/david/.ssh/config\r\ndebug1: /Users/david/.ssh/config line 1: Applying options for 10.59.*\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 10.0.0.99 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25787\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 10.0.0.99 closed.\r\n')
changed: [david-icinga.internal] => changed=true
  ansible_module_results: none
  invocation:
    module_args:
      database_config_file: /etc/icingaweb2/.my.cnf
      database_login_host: 10.0.0.96
      database_login_password: null
      database_login_port: 3306
      database_login_unix_socket: null
      database_login_user: null
      database_name: icingaweb_config
      force: true
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      preferences: null
      state: present
      username: hard
```

This is the content of ` /etc/icingaweb2/.my.cnf`
```
[client]

user = icingaweb_config
password = icingaweb_config
host = 10.0.0.96
```

The mysql database is unfortunately unchanged.
Users created in the web ui are present in the db and work as intended.
Is this working for you?
Let me know if I can provide any more info.

**Comment by bodsch** [comment]
Just one question ... which version did you use?

**Comment by bodsch** [comment]
I created a fix branch: https://github.com/bodsch/ansible-icingaweb2/tree/bug/13-users-are-not-added-to-database

can you check the logfile on the destination system? (`journalctl | grep ansible-icingaweb_database_user`)

**Comment by DavidMorp** [comment]
> journalctl | grep ansible-icingaweb_database_user
```
Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: Invoked with state=present username=VALUE_SPECIFIED_IN_NO_LOG_PARAMETER password=NOT_LOGGING_PARAMETER database_login_host=10.0.0.96 database_name=icingaweb_config database_config_file=/etc/icingaweb2/.my.cnf force=False database_login_port=3306 preferences=None database_login_user=None database_login_password=NOT_LOGGING_PARAMETER database_login_unix_socket=None
Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: config : {'read_default_file': '/etc/icingaweb2/.my.cnf', 'host': '10.0.0.96', 'port': 3306, 'db': 'icingaweb_config'}
Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]:   - error: False | msg: successful connected
Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: query      : insert ignore into icingaweb_user (name, active, password_hash) VALUES ('********', 1, '$5$lUZOIAf/bqJ52RRm$b1HcVU33iyUaydzZjgX1S0T96q.VunNbLQkw0Jjpz63');
Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: = result : '{'changed': True, 'msg': 'user ******** successful inserted'}'
```
Ran with:
```
icingaweb_users:
  - testuser1:
    username: "testuser1"
    password: "testuser1"
```
But no changes on the db unfortunately

**Comment by DavidMorp** [comment]
> Just one question ... which version did you use?

Of the repo? I'm on DavidMorp/ansible-icingaweb2 master (which is now even with your bugfix branch)
Of ansible? 
```
ansible 2.10.8
  config file = None
  configured module search path = ['/Users/dmorpurg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dmorpurg/Library/Python/3.9/lib/python/site-packages/ansible
  executable location = /Users/dmorpurg/Library/Python/3.9/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by bodsch** [comment]
> > Just one question ... which version did you use?
> 
> Of the repo? I'm on DavidMorp/ansible-icingaweb2 master (which is now even with your bugfix branch)

of this repo :)

thanks for your information.

**Comment by bodsch** [comment]
> > journalctl | grep ansible-icingaweb_database_user
> 
> ```
> Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: Invoked with state=present username=VALUE_SPECIFIED_IN_NO_LOG_PARAMETER password=NOT_LOGGING_PARAMETER database_login_host=10.0.0.96 database_name=icingaweb_config database_config_file=/etc/icingaweb2/.my.cnf force=False database_login_port=3306 preferences=None database_login_user=None database_login_password=NOT_LOGGING_PARAMETER database_login_unix_socket=None
> Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: config : {'read_default_file': '/etc/icingaweb2/.my.cnf', 'host': '10.0.0.96', 'port': 3306, 'db': 'icingaweb_config'}
> Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]:   - error: False | msg: successful connected
> Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: query      : insert ignore into icingaweb_user (name, active, password_hash) VALUES ('********', 1, '$5$lUZOIAf/bqJ52RRm$b1HcVU33iyUaydzZjgX1S0T96q.VunNbLQkw0Jjpz63');
> Jun 17 11:39:25 david-icinga.internal ansible-icingaweb_database_user[16525]: = result : '{'changed': True, 'msg': 'user ******** successful inserted'}'
> ```
> 
> Ran with:
> 
> ```
> icingaweb_users:
>   - testuser1:
>     username: "testuser1"
>     password: "testuser1"
> ```
> 
> But no changes on the db unfortunately

Thanks, I'll have to dig deeper on that one.

**Comment by bodsch** [comment]
I think I have the solution.
The update, or forced insert I had not yet implemented.
Since I had never used it, I have never tested it.

But now ... please try once.

**Comment by DavidMorp** [comment]
Thanks for this!
Now it works (moslty)🎉
testuser1 appeared as created because `/etc/icingaweb2/.ansible/user_testuser1.json` was still there, but was not added to the db.
```
TASK [icingaweb : import icingaweb users into database] ********************************************************************************************************************************************************
Friday 18 June 2021  09:16:08 +0200 (0:00:00.778)       0:00:17.221 ***********
ok: [david-icinga.internal] => (item=username: testuser1, active: __omit_place_holder__e552e044b743c61e275650b8a65b4457f39754e6, state: present) => changed=false
  ansible_loop_var: item
  item:
    password: testuser1
    testuser1: null
    username: testuser1
  msg: user, password or active state have not been changed / preference have not been changed
```
using `force: true` successfully added it to the db 👍
```
TASK [icingaweb : import icingaweb users into database] ********************************************************************************************************************************************************
Friday 18 June 2021  09:36:23 +0200 (0:00:00.762)       0:00:15.793 ***********
changed: [david-icinga.internal] => (item=username: testuser1, active: __omit_place_holder__92528ce748db5f9c61c36a64db7828215082bd7a, state: present) => changed=true
  ansible_loop_var: item
  item:
    force: true
    password: testuser1
    testuser1: null
    username: testuser1
  msg: user ******** forced inserted
```
Also new users were added to the db, without the need for `force`.
Since I want the ansible vars are to be an accurate representation of the infrastructure, I will leave`force: true` permanently. On this assumption, I would consider the bug resolved.
With `force:false`, though, the behaviour can be inconsistent. For example:
- if the password has been changed in the web UI but `some_user.json` still matches the vars, `user, password or active state have not been changed / preference have not been changed` is displayed, but it's not accurate
- same if the `some_user.json` is present but the row on the db is not

This could be fixed by:
- creating `some_user.json` from the db at the beginning of the task
- deleting `some_user.json` (optionally) at the end of the task

Thanks again for the quick fix! :)
